routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth::routes();
Auth::routes(['verify' => true]);

/*
Route::get('protege', function () {
    return 'affichage de la route protégé';
})->middleware('verified');
*/
//Route::get('/', 'AdController@home')->name('home')->middleware('verified');
Route::get('/', 'AdController@home')->name('home');


Route::get('a-faire', 'AdController@doPage')->name('dopage');

// Authentication Routes...
Route::prefix('connexion')->group(function () {
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/', 'Auth\LoginController@login');
});
Route::post('deconnexion', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::prefix('enregistrement')->group(function () {
    Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/', 'Auth\RegisterController@register');
});
// Password Reset Routes...
Route::prefix('passe')->group(function () {
    Route::get('change', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('change/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('change', 'Auth\ResetPasswordController@reset')->name('password.update');
});



//
//Route::get('{num}', 'NewsController@show')->name('news.show');

//Route::get('news/{num}/edit', 'NewsController@show')->name('news.edit');



//Route::prefix('news')->group(function () {
    //Route::get('news', 'NewsController@index')->name('news.index');
//});



Route::resource('news', 'NewsController')
//    ->middleware('verified')
    ->parameters(['news' => 'news'    ]);   // pour edit

Route::prefix('news')->group(function () {

    Route::get('destroy/{news}', 'NewsController@destroy')->name('news.destroy');
  //  Route::post('change', 'NewsController@update')->name('news.update');

    /*
    Route::get('{num}', 'NewsController@show')->name('news.show');
    Route::get('/', 'NewsController@index')->name('news.index');
    Route::get('{num}/modif', 'NewsController@show')->name('news.modif');
*/
});


Route::resource('annonces', 'AdController')
    ->parameters(['annonces' => 'ad'    ])   // pour edit
    ->except(['index', 'destroy']);


Route::prefix('annonces')->group(function () {

    // affiche une annonce
    Route::get('{ad}/voir', 'AdController@show')->name('annonces.show');

    // affiche la liste
    Route::get('{region?}/{departement?}/{commune?}', 'AdController@index')->name('annonces.index');
    Route::get('{region?}/{departement?}/{commune?}/{cate?}', 'AdController@index')->name('annonces.index');

    // formulaire de recherche
    Route::post('recherche', 'AdController@search')->name('annonces.search')->middleware('ajax');
});


// message
Route::middleware('ajax')->group(function () {
    Route::post('images-save', 'UploadImagesController@store')->name('save-images');
    Route::delete('images-delete', 'UploadImagesController@destroy')->name('destroy-images');
    Route::get('images-server','UploadImagesController@getServerImages')->name('server-images');

    Route::post('message', 'UserController@message')->name('message');
});

// admin
Route::prefix('admin')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::prefix('annonces')->group(function () {
        Route::get('/', 'AdminController@ads')->name('admin.ads');
        Route::middleware('ajax')->group(function () {
            Route::post('approve/{ad}', 'AdminController@approve')->name('admin.approve');
            Route::post('refuse', 'AdminController@refuse')->name('admin.refuse');
        });

        Route::get('obsoletes', 'AdminController@obsoletes')->name('admin.obsoletes');
    });

    Route::prefix('messages')->group(function () {
        Route::get('/', 'AdminController@messages')->name('admin.messages');
        Route::post('approve/{message}', 'AdminController@messageApprove')->name('admin.message.approve');
        Route::post('refuse', 'AdminController@messageRefuse')->name('admin.message.refuse');
    });

});

Route::prefix('admin/annonces')->group(function () {
    Route::middleware('ajax')->group(function () {
        Route::post('addweek/{ad}', 'AdminController@addWeek')->name('admin.addweek');
        Route::delete('destroy/{ad}', 'AdminController@destroy')->name('admin.destroy');
    });
});


// user
Route::prefix('utilisateur')->middleware('user')->group(function () {
    Route::get('/', 'UserController@index')->name('user.index')->middleware('verified');
    Route::prefix('annonces')->group(function () {
        Route::get('actives', 'UserController@actives')->name('user.actives');
        Route::get('obsoletes', 'UserController@obsoletes')->name('user.obsoletes');
        Route::get('attente', 'UserController@attente')->name('user.attente');
    });
    Route::prefix('profil')->group(function () {
        Route::get('email', 'UserController@emailEdit')->name('user.email.edit');
        Route::put('email', 'UserController@emailUpdate')->name('user.email.update');
        Route::get('donnees', 'UserController@data')->name('user.data');
        Route::get('abonnement', 'SubscriptionController@show')->name('user.subscription.select');
        Route::get('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('annuler', 'SubscriptionController@cancel')->name('user.subscription.cancel');
    });
});

Route::view('group', 'group')->name('group')->middleware('verified');
Route::view('legal', 'legal')->name('legal');
Route::view('confidentialite', 'confidentialite')->name('confidentialite');
Route::view('information', 'information')->name('information');
Route::view('tarif', 'tarif')->name('tarif');


// chat
Route::get('chat', 'ChatsController@index');
Route::get('chat/{user}', 'ChatsController@index')->name('chat.liste');
Route::get('chats', 'ChatsController@fetchMessages');
Route::post('chats', 'ChatsController@sendMessage');

Route::get('locale/{locale}', function ($locale){
    session()->put('locale', $locale);
    return redirect()->back();
});



Route::get('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');

/*
// paypal
Route::get('abonnement', 'PaypalController@index')->name('subscription');
Route::get('paypal/express-checkout', 'PaypalController@expressCheckout')->name('paypal.express-checkout');
Route::get('paypal/express-cancel/{invoice_id?}', 'PaypalController@expressCancel')->name('paypal.express-cancel');
Route::get('paypal/express-checkout-success', 'PaypalController@expressCheckoutSuccess');
Route::post('paypal/notify', 'PaypalController@notify');
*/


// Stripe

Route::get('abonnement', 'SubscriptionController@show')->name('abonnement');
Route::post('order-post', ['as'=>'order-post','uses'=>'SubscriptionController@orderPost']);

resources/views/partials/ad.blade.php
<div class="card h-100 border-0 shadow card-zoom">
    <div class="card-img-top overflow-hidden grient-overlay ad-card-img-div-top">
        @if($ad->photos->isNotEmpty())
            <img src="{{ asset('thumbs/' . $ad->photos->first()->filename) }}" alt="" class="rounded img-fluid" width="100%">
        @else
            <img src="{{ asset('thumbs/nopicture.jpg') }}" alt="" class="img-fluid">
        @endif
        <a href="{{ route('annonces.show', $ad->id) }}" class="tile-link"></a>
        <!--
    <div class="card-img-overlay-top text-right"><a href="javascript: void();" class="card-fav-icon position-relative z-index-40">
            <svg class="svg-icon text-white">
                <use xlink:href="#heart-1"> </use>
            </svg></a>
    </div>
    -->
    </div>
    <div class="card-body d-flex align-items-center">
        <div class="w-100">
            <h6 class="card-title">{{ $ad->title }}</h6>
            <div class="d-flex card-subtitle mb-3">
                <p class="flex-grow-1 mb-0 text-muted text-sm ad-text-small">{{ $ad->category->name }}</p>
                <!--
                <p class="flex-shrink-1 mb-0 card-stars text-xs text-right">
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-warning"></i>
                    <i class="fa fa-star text-gray-300"></i>
                    <i class="fa fa-star text-gray-300"></i>
                </p>
                -->
            </div>
            <p class="text-gray-700 text-sm my-3 ad-text">

                {{ strlen($ad->texte) > 50 ? substr($ad->texte, 0, 50).'...' : $ad->texte }}
            </p>

            <p class="text-gray-500 text-sm my-3 align-bottom ad-text-small">
                <i class="fa fa-road mr-2"></i>{{ $ad->commune_name . ' (' . $ad->commune_postal . ')'}}<br>
                <i class="far fa-clock mr-2"></i>{{ $ad->created_at->format('d/m/Y H:i') }}
            </p>
            <a href="{{ route('annonces.show', $ad->id) }}" class="tile-link"></a>
        </div>
    </div>
</div>

resources/views/partials/ads.blade.php
<div class="row">
@foreach($ads as $ad)
        <div class="col-sm-6 col-lg-4 mb-5 hover-animate">
        @include('partials.ad', ['ad' =>$ad])
        </div>
@endforeach
</div>

<div class="d-flex">
    <div class="mx-auto">
        {{ $ads->links() }}
    </div>
</div>

resources/views/partials/alerts.blade.php
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ $title }}</h1>
</div>
@if(session()->has('status'))
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ session('status') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
@endif

resources/views/partials/form-group.blade.php
<div class="form-group">
    <label for="{{ $name }}">{{ $title }}</label>
    <input id="{{ $name }}" type="{{ $type }}" class="form-control{{ $errors->has($name) ? ' is-invalid' : '' }}"
           name="{{ $name }}" value="{{ old($name, isset($value) ? $value : '') }}" {{ $required ? 'required' : ''}}>
    @if ($errors->has($name))
        <div class="invalid-feedback">
            {{ $errors->first($name) }}
        </div>
    @endif
</div>

resources/views/partials/message.blade.php
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="message" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <form id="messageForm" method="POST" action="{{ $url }}">
                @csrf
                <div class="modal-body">
                    @guest
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            Vous n'êtes pas connecté. Votre message sera modéré avant expédition.
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endguest
                    <input id="id" name="id" type="hidden" value="{{ isset($ad) ? $ad->id : '' }}">
                    <div class="form-group">
                        <label for="texte">Entrez ici votre message</label>
                        <textarea class="form-control" id="message" name="message" rows="3" required>{{ old('texte', isset($value) ? $value : '') }}</textarea>
                        <div id="messageError" class="invalid-feedback"></div>
                    </div>
                    @guest
                        <div class="form-group">
                            <label for="email">Votre email pour vous contacter</label>
                            <input type="email" class="form-control" name=email id="email" required>
                            <div id="emailError" class="invalid-feedback"></div>
                        </div>
                    @endguest
                </div>
                <div class="modal-footer">
                    <div id="buttons">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                        <button type="submit" class="btn btn-primary">Envoyer</button>
                    </div>
                    <i id="icon" class="fas fa-spinner fa-pulse fa-2x" style="display: none"></i>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/partials/script-add-del-view.blade.php
<script>
    $(() => {
        const init = (e) => {
            e.preventDefault();
            let that = $(e.currentTarget);
            that.hide();
            that.closest('td').find('i.fa-spinner').show();
            return that;
        }
        const alertServer = () => {
            that.show();
            that.closest('td').find('i.fa-spinner').hide();
            $('.alert-warning').removeClass('d-none').addClass('show');
        }
        $('.alert-warning button').click(() => {
            $('.alert-warning').addClass('d-none').removeClass('show');
        });
        $('.btn-danger').click((e) => {
            that = init(e);
            $.ajax({
                method: 'delete',
                url: that.attr('href'),
            })
                .done(() => {
                    document.location.reload(true);
                })
                .fail(() => {
                    alertServer();
                });
        });
        $('.btn-success').click((e) => {
            that = init(e);
            $.post(that.attr('href'))
                .done((data) => {
                    that.show();
                    that.closest('td').find('i.fa-spinner').hide();
                    that.closest('tr').find('td.date-id').text(data.limit);
                    if(data.ok) that.closest('tr').addClass('table-success');
                })
                .fail(() => {
                    alertServer();
                });
        });
    })
</script>

resources/views/partials/script.blade.php
<script>
    $(() => {
        const toggleButtons = () => {
            $('#icon').toggle();
            $('#buttons').toggle();
        }
        $('.alert-success button').click(() => {
            $('.alert-success').addClass('d-none').removeClass('show');
        });
        $('.alert-warning button').click(() => {
            $('.alert-warning').addClass('d-none').removeClass('show');
        });
        $('.btn-success').click((e) => {
            e.preventDefault();
            let that = $(e.currentTarget);
            that.hide();
            that.closest('td').find('i.fa-spinner').show();
            $.post(that.attr('href'))
                .done((data) => {
                    document.location.reload(true);
                })
                .fail(() => {
                    $('.alert-warning').removeClass('d-none').addClass('show');
                    that.show();
                    that.closest('td').find('i.fa-spinner').hide();
                });
        });
        $('.btn-danger').click((e) => {
            e.preventDefault();
            $('#id').val($(e.currentTarget).attr('data-id'));
            $('#messageModal').modal();
        });
        $('#messageForm').submit((e) => {
            let that = e.currentTarget;
            e.preventDefault();
            $('#message').removeClass('is-invalid');
            $('.invalid-feedback').html('');
            toggleButtons();
            $.ajax({
                method: $(that).attr('method'),
                url: $(that).attr('action'),
                data: $(that).serialize()
            })
                .done((data) => {
                    document.location.reload(true);
                })
                .fail((data) => {
                    toggleButtons();
                    if(data.status == 422) {
                        $.each(data.responseJSON.errors, function (i, error) {
                            $(document)
                                .find('[name="' + i + '"]')
                                .addClass('is-invalid')
                                .next()
                                .append(error[0]);
                        });
                    } else {
                        $('#messageModal').modal('hide');
                        $('.alert-warning').removeClass('d-none').addClass('show');
                    }
                });
        });
    })
</script>

resources/views/partials/table-add-del-view.blade.php
<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-light">
        <tr>
            <th scope="col">Titre</th>
            <th scope="col">Limite</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @foreach ($ads as $ad)
            <tr id="{{ $ad->id }}">
                <td>{{ $ad->title }}</td>
                <td class="date-id">{{ date_create($ad->limit)->format('d-m-Y') }}</td>
                <td class="float-right">
                    <a class="btn btn-primary btn-sm" href="{{ route('annonces.show', $ad->id) }}" target="_blank" role="button" data-toggle="tooltip" title="Voir l'annonce"><i class="fas fa-eye"></i></a>
                    @isset($edit)
                        <a class="btn btn-warning btn-sm" href="{{ route('annonces.edit', $ad->id) }}" role="button" data-toggle="tooltip" title="Modifier l'annonce"><i class="fas fa-edit"></i></a>
                    @endisset
                    <i class="fas fa-spinner fa-pulse fa-lg" style="display: none"></i>
                    @empty($noAdd)
                        <a class="btn btn-success btn-sm" href="{{ route('admin.addweek', $ad->id) }}" role="button" data-id="{{ $ad->id }}" data-toggle="tooltip" title="Ajouter une semaine"><i class="fas fa-arrow-alt-circle-up"></i></a>
                    @endisset
                    <a class="btn btn-danger btn-sm" href="{{ route('admin.destroy', $ad->id) }}" role="button" data-id="{{ $ad->id }}" data-toggle="tooltip" title="Supprimer l'annonce"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
<div class="d-flex">
    <div class="mx-auto">
        {{ $ads->links() }}
    </div>
</div>