routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth::routes();
Auth::routes(['verify' => true]);

/*
Route::get('protege', function () {
    return 'affichage de la route protégé';
})->middleware('verified');
*/
//Route::get('/', 'AdController@home')->name('home')->middleware('verified');
Route::get('/', 'AdController@home')->name('home');


Route::get('a-faire', 'AdController@doPage')->name('dopage');

// Authentication Routes...
Route::prefix('connexion')->group(function () {
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/', 'Auth\LoginController@login');
});
Route::post('deconnexion', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::prefix('enregistrement')->group(function () {
    Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/', 'Auth\RegisterController@register');
});
// Password Reset Routes...
Route::prefix('passe')->group(function () {
    Route::get('change', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('change/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('change', 'Auth\ResetPasswordController@reset')->name('password.update');
});



//
//Route::get('{num}', 'NewsController@show')->name('news.show');

//Route::get('news/{num}/edit', 'NewsController@show')->name('news.edit');



//Route::prefix('news')->group(function () {
    //Route::get('news', 'NewsController@index')->name('news.index');
//});



Route::resource('news', 'NewsController')
//    ->middleware('verified')
    ->parameters(['news' => 'news'    ]);   // pour edit

Route::prefix('news')->group(function () {

    Route::get('destroy/{news}', 'NewsController@destroy')->name('news.destroy');
  //  Route::post('change', 'NewsController@update')->name('news.update');

    /*
    Route::get('{num}', 'NewsController@show')->name('news.show');
    Route::get('/', 'NewsController@index')->name('news.index');
    Route::get('{num}/modif', 'NewsController@show')->name('news.modif');
*/
});


Route::resource('annonces', 'AdController')
    ->parameters(['annonces' => 'ad'    ])   // pour edit
    ->except(['index', 'destroy']);


Route::prefix('annonces')->group(function () {

    // affiche une annonce
    Route::get('{ad}/voir', 'AdController@show')->name('annonces.show');

    // affiche la liste
    Route::get('{region?}/{departement?}/{commune?}', 'AdController@index')->name('annonces.index');
    Route::get('{region?}/{departement?}/{commune?}/{cate?}', 'AdController@index')->name('annonces.index');

    // formulaire de recherche
    Route::post('recherche', 'AdController@search')->name('annonces.search')->middleware('ajax');
});


// message
Route::middleware('ajax')->group(function () {
    Route::post('images-save', 'UploadImagesController@store')->name('save-images');
    Route::delete('images-delete', 'UploadImagesController@destroy')->name('destroy-images');
    Route::get('images-server','UploadImagesController@getServerImages')->name('server-images');

    Route::post('message', 'UserController@message')->name('message');
});

// admin
Route::prefix('admin')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::prefix('annonces')->group(function () {
        Route::get('/', 'AdminController@ads')->name('admin.ads');
        Route::middleware('ajax')->group(function () {
            Route::post('approve/{ad}', 'AdminController@approve')->name('admin.approve');
            Route::post('refuse', 'AdminController@refuse')->name('admin.refuse');
        });

        Route::get('obsoletes', 'AdminController@obsoletes')->name('admin.obsoletes');
    });

    Route::prefix('messages')->group(function () {
        Route::get('/', 'AdminController@messages')->name('admin.messages');
        Route::post('approve/{message}', 'AdminController@messageApprove')->name('admin.message.approve');
        Route::post('refuse', 'AdminController@messageRefuse')->name('admin.message.refuse');
    });

});

Route::prefix('admin/annonces')->group(function () {
    Route::middleware('ajax')->group(function () {
        Route::post('addweek/{ad}', 'AdminController@addWeek')->name('admin.addweek');
        Route::delete('destroy/{ad}', 'AdminController@destroy')->name('admin.destroy');
    });
});


// user
Route::prefix('utilisateur')->middleware('user')->group(function () {
    Route::get('/', 'UserController@index')->name('user.index')->middleware('verified');
    Route::prefix('annonces')->group(function () {
        Route::get('actives', 'UserController@actives')->name('user.actives');
        Route::get('obsoletes', 'UserController@obsoletes')->name('user.obsoletes');
        Route::get('attente', 'UserController@attente')->name('user.attente');
    });
    Route::prefix('profil')->group(function () {
        Route::get('email', 'UserController@emailEdit')->name('user.email.edit');
        Route::put('email', 'UserController@emailUpdate')->name('user.email.update');
        Route::get('donnees', 'UserController@data')->name('user.data');
        Route::get('abonnement', 'SubscriptionController@show')->name('user.subscription.select');
        Route::get('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('annuler', 'SubscriptionController@cancel')->name('user.subscription.cancel');
    });
});

Route::view('group', 'group')->name('group')->middleware('verified');
Route::view('legal', 'legal')->name('legal');
Route::view('confidentialite', 'confidentialite')->name('confidentialite');
Route::view('information', 'information')->name('information');
Route::view('tarif', 'tarif')->name('tarif');


// chat
Route::get('chat', 'ChatsController@index');
Route::get('chat/{user}', 'ChatsController@index')->name('chat.liste');
Route::get('chats', 'ChatsController@fetchMessages');
Route::post('chats', 'ChatsController@sendMessage');

Route::get('locale/{locale}', function ($locale){
    session()->put('locale', $locale);
    return redirect()->back();
});



Route::get('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');

/*
// paypal
Route::get('abonnement', 'PaypalController@index')->name('subscription');
Route::get('paypal/express-checkout', 'PaypalController@expressCheckout')->name('paypal.express-checkout');
Route::get('paypal/express-cancel/{invoice_id?}', 'PaypalController@expressCancel')->name('paypal.express-cancel');
Route::get('paypal/express-checkout-success', 'PaypalController@expressCheckoutSuccess');
Route::post('paypal/notify', 'PaypalController@notify');
*/


// Stripe

Route::get('abonnement', 'SubscriptionController@show')->name('abonnement');
Route::post('order-post', ['as'=>'order-post','uses'=>'SubscriptionController@orderPost']);

resources/views/layouts/admin.blade.php
@include('layouts.back-header')
<body id="page-top">
<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('/') }}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fab fa-earlybirds fa-2x"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Annonces</div>
        </a>
        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item @if(request()->route()->getName() == 'user.index') active @endif">
            <a class="nav-link" href="{{ route('user.index') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Gestion Compte</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Articles
        </div>
        <li class="nav-item @if(request()->route()->getName() == 'admin.ads') active @endif">
            <a class="nav-link" href="{{ route('news.create') }}">
                <i class="fas fa-fw fa-book-open"></i>
                <span>Créer</span></a>
        </li>
        <div class="sidebar-heading">
            Annonces
        </div>
        <li class="nav-item @if(request()->route()->getName() == 'admin.ads') active @endif">
            <a class="nav-link" href="{{ route('admin.ads') }}">
                <i class="fas fa-fw fa-question"></i>
                <span>A modérer</span></a>
        </li>
        <li class="nav-item @if(request()->route()->getName() == 'admin.obsoletes') active @endif">
            <a class="nav-link" href="{{ route('admin.obsoletes') }}">
                <i class="fas fa-fw fa-hourglass-end"></i>
                <span>Obsolètes</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Messages
        </div>
        <li class="nav-item @if(request()->route()->getName() == 'admin.messages') active @endif">
            <a class="nav-link" href="{{ route('admin.messages') }}">
                <i class="fas fa-fw fa-question"></i>
                <span>A modérer</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Déconnexion
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">
                @yield('content')
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Annonces 2019</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->
@include('layouts.back-footer')

resources/views/layouts/back-footer.blade.php
<script src="{{ asset('js/sb-admin.js') }}"></script>
<script>
    $(function () {
        $('[data-toggle="tooltip"]').tooltip();
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    })
</script>
@yield('script')
</body>
</html>

resources/views/layouts/back-header.blade.php
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Annonces</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="{{ asset('css/sb-admin.css') }}" rel="stylesheet">
</head>

resources/views/layouts/user.blade.php
@include('layouts.back-header')
<body id="page-top">
<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('/') }}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fab fa-earlybirds fa-2x"></i>
            </div>
            <div class="sidebar-brand-text mx-3">Annonces</div>
        </a>
        <!-- Divider -->
        <hr class="sidebar-divider my-0">
        <!-- Nav Item - Dashboard -->
        <li class="nav-item @if(request()->route()->getName() == 'user.index') active @endif">
            <a class="nav-link" href="{{ route('user.index') }}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Gestion du compte</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Annonces
        </div>
        <li class="nav-item @if(request()->route()->getName() == 'user.actives') active @endif">
            <a class="nav-link" href="{{ route('user.actives') }}">
                <i class="fas fa-fw fa-hiking"></i>
                <span>Actives</span></a>
        </li>
        <li class="nav-item @if(request()->route()->getName() == 'user.attente') active @endif">
            <a class="nav-link" href="{{ route('user.attente') }}">
                <i class="fas fa-fw fa-hourglass-start"></i>
                <span>En attente</span></a>
        </li>
        <li class="nav-item @if(request()->route()->getName() == 'user.obsoletes') active @endif">
            <a class="nav-link" href="{{ route('user.obsoletes') }}">
                <i class="fas fa-fw fa-hourglass-end"></i>
                <span>Obsolètes</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Heading -->
        <div class="sidebar-heading">
            Profil
        </div>
        <li class="nav-item @if(request()->route()->getName() == 'subscription') active @endif">
            <a class="nav-link" href="{{  route('abonnement') }}">
                <i class="fas fa-fw fa-credit-card"></i>
                <span>Abonnement</span></a>
        </li>
        <li class="nav-item @if(request()->route()->getName() == 'user.email.edit') active @endif">
            <a class="nav-link" href="{{ route('user.email.edit') }}">
                <i class="fas fa-fw fa-at"></i>
                <span>Email</span></a>
        </li>
        <li class="nav-item @if(request()->route()->getName() == 'user.data') active @endif">
            <a class="nav-link" href="{{ route('user.data') }}">
                <i class="fas fa-fw fa-database"></i>
                <span>Mes données</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>
                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="d-lg-inline text-gray-600 small">{{ auth()->user()->name }}</span>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Déconnexion
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                </ul>
            </nav>
            <!-- End of Topbar -->
            <!-- Begin Page Content -->
            <div class="container-fluid">
                @yield('content')
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->
        <!-- Footer -->
        <footer class="sticky-footer bg-white">
            <div class="container my-auto">
                <div class="copyright text-center my-auto">
                    <span>Copyright &copy; Annonces 2019</span>
                </div>
            </div>
        </footer>
        <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
</div>
<!-- End of Page Wrapper -->
@include('layouts.back-footer')