routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth::routes();
Auth::routes(['verify' => true]);

/*
Route::get('protege', function () {
    return 'affichage de la route protégé';
})->middleware('verified');
*/
//Route::get('/', 'AdController@home')->name('home')->middleware('verified');
Route::get('/', 'AdController@home')->name('home');


Route::get('a-faire', 'AdController@doPage')->name('dopage');

// Authentication Routes...
Route::prefix('connexion')->group(function () {
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/', 'Auth\LoginController@login');
});
Route::post('deconnexion', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::prefix('enregistrement')->group(function () {
    Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/', 'Auth\RegisterController@register');
});
// Password Reset Routes...
Route::prefix('passe')->group(function () {
    Route::get('change', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('change/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('change', 'Auth\ResetPasswordController@reset')->name('password.update');
});



//
//Route::get('{num}', 'NewsController@show')->name('news.show');

//Route::get('news/{num}/edit', 'NewsController@show')->name('news.edit');



//Route::prefix('news')->group(function () {
    //Route::get('news', 'NewsController@index')->name('news.index');
//});



Route::resource('news', 'NewsController')
//    ->middleware('verified')
    ->parameters(['news' => 'news'    ]);   // pour edit

Route::prefix('news')->group(function () {

    Route::get('destroy/{news}', 'NewsController@destroy')->name('news.destroy');
  //  Route::post('change', 'NewsController@update')->name('news.update');

    /*
    Route::get('{num}', 'NewsController@show')->name('news.show');
    Route::get('/', 'NewsController@index')->name('news.index');
    Route::get('{num}/modif', 'NewsController@show')->name('news.modif');
*/
});


Route::resource('annonces', 'AdController')
    ->parameters(['annonces' => 'ad'    ])   // pour edit
    ->except(['index', 'destroy']);


Route::prefix('annonces')->group(function () {

    // affiche une annonce
    Route::get('{ad}/voir', 'AdController@show')->name('annonces.show');

    // affiche la liste
    Route::get('{region?}/{departement?}/{commune?}', 'AdController@index')->name('annonces.index');
    Route::get('{region?}/{departement?}/{commune?}/{cate?}', 'AdController@index')->name('annonces.index');

    // formulaire de recherche
    Route::post('recherche', 'AdController@search')->name('annonces.search')->middleware('ajax');
});


// message
Route::middleware('ajax')->group(function () {
    Route::post('images-save', 'UploadImagesController@store')->name('save-images');
    Route::delete('images-delete', 'UploadImagesController@destroy')->name('destroy-images');
    Route::get('images-server','UploadImagesController@getServerImages')->name('server-images');

    Route::post('message', 'UserController@message')->name('message');
});

// admin
Route::prefix('admin')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::prefix('annonces')->group(function () {
        Route::get('/', 'AdminController@ads')->name('admin.ads');
        Route::middleware('ajax')->group(function () {
            Route::post('approve/{ad}', 'AdminController@approve')->name('admin.approve');
            Route::post('refuse', 'AdminController@refuse')->name('admin.refuse');
        });

        Route::get('obsoletes', 'AdminController@obsoletes')->name('admin.obsoletes');
    });

    Route::prefix('messages')->group(function () {
        Route::get('/', 'AdminController@messages')->name('admin.messages');
        Route::post('approve/{message}', 'AdminController@messageApprove')->name('admin.message.approve');
        Route::post('refuse', 'AdminController@messageRefuse')->name('admin.message.refuse');
    });

});

Route::prefix('admin/annonces')->group(function () {
    Route::middleware('ajax')->group(function () {
        Route::post('addweek/{ad}', 'AdminController@addWeek')->name('admin.addweek');
        Route::delete('destroy/{ad}', 'AdminController@destroy')->name('admin.destroy');
    });
});


// user
Route::prefix('utilisateur')->middleware('user')->group(function () {
    Route::get('/', 'UserController@index')->name('user.index')->middleware('verified');
    Route::prefix('annonces')->group(function () {
        Route::get('actives', 'UserController@actives')->name('user.actives');
        Route::get('obsoletes', 'UserController@obsoletes')->name('user.obsoletes');
        Route::get('attente', 'UserController@attente')->name('user.attente');
    });
    Route::prefix('profil')->group(function () {
        Route::get('email', 'UserController@emailEdit')->name('user.email.edit');
        Route::put('email', 'UserController@emailUpdate')->name('user.email.update');
        Route::get('donnees', 'UserController@data')->name('user.data');
        Route::get('abonnement', 'SubscriptionController@show')->name('user.subscription.select');
        Route::get('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('annuler', 'SubscriptionController@cancel')->name('user.subscription.cancel');
    });
});

Route::view('group', 'group')->name('group')->middleware('verified');
Route::view('legal', 'legal')->name('legal');
Route::view('confidentialite', 'confidentialite')->name('confidentialite');
Route::view('information', 'information')->name('information');
Route::view('tarif', 'tarif')->name('tarif');


// chat
Route::get('chat', 'ChatsController@index');
Route::get('chat/{user}', 'ChatsController@index')->name('chat.liste');
Route::get('chats', 'ChatsController@fetchMessages');
Route::post('chats', 'ChatsController@sendMessage');

Route::get('locale/{locale}', function ($locale){
    session()->put('locale', $locale);
    return redirect()->back();
});



Route::get('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');

/*
// paypal
Route::get('abonnement', 'PaypalController@index')->name('subscription');
Route::get('paypal/express-checkout', 'PaypalController@expressCheckout')->name('paypal.express-checkout');
Route::get('paypal/express-cancel/{invoice_id?}', 'PaypalController@expressCancel')->name('paypal.express-cancel');
Route::get('paypal/express-checkout-success', 'PaypalController@expressCheckoutSuccess');
Route::post('paypal/notify', 'PaypalController@notify');
*/


// Stripe

Route::get('abonnement', 'SubscriptionController@show')->name('abonnement');
Route::post('order-post', ['as'=>'order-post','uses'=>'SubscriptionController@orderPost']);

app/Models/Ad.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Ad extends Model
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'texte',
        'prix',
        'telephone',
        'category_id',
        'region_id',
        'user_id',
        'departement',
        'commune',
        'commune_name',
        'commune_postal',
        'adresse',
        'pseudo',
        'email',
        'limit',
        'active',
    ];
    /**
     * Get the region that owns the ad.
     */
    public function region()
    {
        return $this->belongsTo(Region::class);
    }
    /**
     * Get the category that owns the ad.
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    /**
     * Get the photos for the ad.
     */
    public function photos()
    {
        return $this->hasMany(Upload::class);
    }
}

app/Http/Controllers/AdController.php
<?php

namespace App\Http\Controllers;


use App\Repositories\ParameterRepository;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Models\Category;
use App\Models\Region;
use App\Models\Ad;
use App\Models\User;
use App\Model\Parameter;

use App\Repositories\AdRepository;
use App\Repositories\NewsRepository;

use App\Http\Requests\AdStore;
use Carbon\Carbon;
use App\Models\Upload;

use App\Http\Requests\AdUpdate;

class AdController extends Controller
{

    /**
     * Ad repository.
     *
     * @var App\Repositories\AdRepository
     */
    protected $adRepository;
    protected $newsRepository;
    protected $parameterRepository;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(AdRepository $adRepository, NewsRepository $newsRepository, ParameterRepository $parameterRepository)
    {
        $this->adRepository = $adRepository;
        $this->newsRepository = $newsRepository;
        $this->parameterRepository = $parameterRepository;
    }



    /**
     * affiche la liste de 8 annonces sur la page d'accueil
     * affiche les articles
     */
    public function home()
    {
        $mode_children = false;
        if (auth()->check() == true){
            $mode_children = auth()->user()->mode_children;
        }

        $ads = $this->adRepository->last(8);
        $adsClub = $this->adRepository->club(10);
        $news = $this->newsRepository->last(10, 'news');
        $coverage = $this->newsRepository->last(1, 'coverage');
        $video_param = $this->parameterRepository->getParam('', 'VIDEO')->get()->toArray();
        $video = $video_param[0]['value'];

        $data = Category::select('code', 'id')->oldest('name')->get()->toArray();
        $categories = array();
        foreach ($data as $item) {
            $categories[$item['id']] = $item['code'];
        }

        $data = Region::select('id','code','name','slug')->oldest('name')->get()->toArray();
        $regions = array();

        foreach ($data as $item) {
            $regions[$item['slug']] = $item['name'];
        }

        return view('home', compact('ads', 'adsClub', 'categories', 'regions', 'news', 'coverage', 'mode_children', 'video'));
    }


    /**
     * Search ads.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  String  $slug
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
       setlocale (LC_TIME, 'fr_FR');
       $ads = $this->adRepository->search($request);

       return view('partials.ads', compact('ads'));
    }

    /**
     * Affiche la liste des annonces sur la page annonces
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  String  $regionSlug
     * @param  Integer  $departementCode
     * @param  Integer  $communeCode
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $regionSlug = null, $departement = null, $commune = null)
    {

        $category = 0;
        $categories = Category::select('name', 'id')->oldest('name')->get();
        $regions = Region::select('id','code','name','slug')->oldest('name')->get();

        if ($request->input('region') !== '')
            $regionSlug = $request->input('region');

        if ($request->input('category') !== null)
            $category = $request->input('category');

        if ($request->input('departement') !== null)
            $departement = $request->input('departement');

        if ($request->input('commune') !== null)
            $commune = $request->input('commune');

        $region = $regionSlug ? Region::whereSlug($regionSlug)->firstOrFail() : 0;

        $page = $request->query('page', 0);

        return view('ads.list', compact('categories', 'regions', 'region', 'departement', 'commune', 'page', 'category'));
    }

    /**
     * affiche la page pour creer une annonce
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if(!$request->session()->has('index')) {
            $request->session()->put('index', Str::random(30));
        }
        $categories = Category::select('name', 'id')->oldest('name')->get();

        $regions = Region::oldest('name')->get();
        return view('ads.create', compact('categories', 'regions'));
    }

    /**
     * enregistre la nouvelle annonce
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdStore $request)
    {
        $commune = json_decode(file_get_contents('https://geo.api.gouv.fr/communes/' . $request->commune), true);
        $ad = $this->adRepository->create([
            'title' => $request->title,
            'texte' => $request->texte,
            'telephone' => $request->phone,
            'category_id' => $request->category,
            'region_id' => $request->region,
            'departement' => $request->departement,
            'commune' => $request->commune,
            'commune_name' => $commune['nom'],
            'commune_postal' => $commune['codesPostaux'][0],
            'prix' => $request->prix,
            'adresse' => $request->adresse,
            'user_id' => auth()->check() ? auth()->id() : 0,
            'pseudo' => auth()->check() ? auth()->user()->name :$request->pseudo,
            'email' => auth()->check() ? auth()->user()->email : $request->email,
            'limit' => Carbon::now()->addWeeks($request->limit),

        ]);

        if($request->session()->has('index')) {
            $index = $request->session()->get('index');

            Upload::whereIndex($index)->update(['ad_id' => $ad->id, 'index' => 0]);
        }
        return view('adconfirm');
    }

    /**
     * affiche une annonce
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Ad $ad)
    {
        $this->authorize('show', $ad);
        $photos = $this->adRepository->getPhotos($ad);
        return view('ads.show', compact('ad', 'photos'));
    }


    /**
     * affiche la page pour modifier une annonce
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Ad $ad)
    {
        //$this->authorize('show', $ad);
        return view('ads.edit', compact('ad'));
    }

    /**
     * modifie une annonce
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdUpdate $request, Ad $ad)
    {
        $this->authorize('manage', $ad);
        $this->adRepository->update($ad, $request->all());
        $request->session()->flash('status', "L'annonce a bien été modifiée.");
        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }


    /**
     * Display a listing actualité.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  String  $regionSlug
     * @param  Integer  $departementCode
     * @param  Integer  $communeCode
     * @return \Illuminate\Http\Response
     */
    public function doPage()
    {

       return view('doPage');
    }



}

resources/views/ads/edit.blade.php
@extends('layouts.app')
@section('content')



    <div class="container">
        <div class="card bg-light">
            <h5 class="card-header">Votre annonce</h5>
            <div class="card-body">
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    Vous ne pouvez modifier que le titre et le texte de votre annonce.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                @if(session()->has('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <form method="POST" action="{{ route('annonces.update', $ad->id) }}">
                    @method('PUT')
                    @csrf
                    @include('partials.form-group', [
                        'title' => 'Titre',
                        'type' => 'text',
                        'name' => 'title',
                        'value' => $ad->title,
                        'required' => true,
                    ])
                    <div class="form-group">
                        <label for="texte">Texte</label>
                        <textarea class="form-control{{ $errors->has('texte') ? ' is-invalid' : '' }} tinymce-editor" id="texte" name="texte" rows="3">{{ old('texte', isset($value) ? $value : $ad->texte) }}</textarea>
                        @if ($errors->has('texte'))
                            <div class="invalid-feedback">
                                {{ $errors->first('texte') }}
                            </div>
                        @endif
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Valider</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://cdn.tiny.cloud/1/8gw0lshon0bn94yzknjer4d2p46xizbxm2r9yp1v6rglyawn/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: 'textarea.tinymce-editor',
            //height: 100,
            menubar: false,
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | formatselect | ' +
                'bold italic backcolor | help',
            toolbar_mode: 'floating'
        });
    </script>

@endsection

resources/views/ads/list.blade.php
@extends('layouts.app')
@section('content')

    <div id="app">
        @if($region)
            <div id="start"
                 data-category="{{ $category }}"
                 data-id={{ $region->id }}
                 data-code="{{ $region->code }}"
                 data-slug="{{ $region->slug }}"
                 @if($departement)
                   data-departement="{{ $departement }}"
                     @if($commune)
                       data-commune="{{ $commune }}"
                     @endif
                 @endif
        @else
                <div id="start"
                     data-category="{{ $category }}"
                     data-id=0


        @endif

        @if($page != 0)
          data-page="{{ $page }}"
        @endif>

    </div>
        <ad url="{{ route('annonces.search') }}" :categories="{{ $categories }}" :regions="{{ $regions }}" :category="{{ $category }}" ref="adComp"></ad>

@endsection
@section('script')
<script src="{{ asset('js/vue.js') }}"></script>
@endsection

resources/views/ads/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container py-5">
        <div id="massageOk" class="alert alert-success" role="alert" style="display: none">
            Votre message a été pris en compte et sera envoyé rapidement
        </div>
        @include('partials.message', ['url' => route('message')])
        @include('chat.modal')

        <div class="row">
            <div class="col-lg-8">
                <div class="text-block">
                    <p class="text-primary">
                        <i class="fa-map-marker-alt fa mr-1"></i>
                        {{ $ad->commune_name . ' (' . $ad->commune_postal . ')'}}
                    </p>
                    <h1>{{ $ad->title }}</h1>
                    <p class="text-muted text-uppercase mb-4">{{ $ad->category->name }}</p>
                    <ul class="list-inline text-sm mb-4">
                        <li class="list-inline-item mr-3">
                            <i class="fa fa-user mr-1 text-secondary"></i>
                            Annonce déposée par {{ $ad->pseudo }} le {{ $ad->created_at->calendar() }}
                        </li>
                    </ul>
                    <p class="text-muted font-weight-light">
                        {!! $ad->texte !!}
                    </p>
                </div>

                <div class="text-block">
                    <h5 class="mb-4" >Ma galerie photo</h5>
                    <div class="row gallery mb-3 ml-n1 mr-n1">
                        @if($photos->isNotEmpty())
                            @if($photos->count() > 0)
                                    @foreach ($photos as $photo)
                                        <div class="col-lg-4 col-6 px-1 mb-2">
                                            <a href="{{ asset('/images/' . $photo->filename) }}" data-fancybox="gallery" title="Outside">
                                                <img src="{{ asset('/images/' . $photo->filename) }}" alt="..." class="img-fluid">
                                            </a>
                                        </div>
                                    @endforeach
                            @endif
                        @endif
                    </div>
                </div>

                <!--
                <div class="text-block">
                    <p class="subtitle text-sm text-primary">Avis reçut de cette annonce</p>
                    <h5 class="mb-4">Liste des commentaires</h5>
                    <div class="media d-block d-sm-flex review">
                        <div class="text-md-center mr-4 mr-xl-5"><img src="img/avatar/avatar-8.jpg" alt="Padmé Amidala" class="d-block avatar avatar-xl p-2 mb-2"><span class="text-uppercase text-muted text-sm">Dec 2018</span></div>
                        <div class="media-body">
                            <h6 class="mt-2 mb-1">Marine cottreau</h6>
                            <div class="mb-2"><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i>
                            </div>
                            <p class="text-muted text-sm">woow bzh hozhoazf j'ai adoré shf hsofhs oh shf jhqosfoqhsoifhoqhsiqoishfoiqhosihfqoihsoihqoifhsoiqhsifhqosihfoqihsoqhsiohf    </p>
                        </div>
                    </div>
                    <div class="media d-block d-sm-flex review">
                        <div class="text-md-center mr-4 mr-xl-5"><img src="img/avatar/avatar-2.jpg" alt="Luke Skywalker" class="d-block avatar avatar-xl p-2 mb-2"><span class="text-uppercase text-muted text-sm">Dec 2018</span></div>
                        <div class="media-body">
                            <h6 class="mt-2 mb-1">Patrick le borgne</h6>
                            <div class="mb-2"><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-primary"></i><i class="fa fa-xs fa-star text-gray-200"></i>
                            </div>
                            <p class="text-muted text-sm">woooooooooq   ofh oazhf oahzofha oizhfoiah ezfuzoa puhez pfgzfu  pazoue fpugapuzge fpuagz epufguagz epufgzug epoif gapugz peufaz uepf  iauzg epfiugzeuf piauzg epufgapiuzgepfugzpiuegfiuzeg fpazieugf pizug efpiuaz pf aze    </p>
                        </div>
                    </div>

                    <div class="py-5">
                        <div id="leaveReview" class="collapse mt-4">
                            <h5 class="mb-4">Posté un commentaire</h5>
                            <form id="contact-form" method="get" action="#" class="form">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="name" class="form-label">Votre nom</label>
                                            <input type="text" name="name" id="name" placeholder="Votre nom" required="required" class="form-control">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label for="rating" class="form-label">Votre notre</label>
                                            <select name="rating" id="rating" class="custom-select focus-shadow-0">
                                                <option value="5">&#9733;&#9733;&#9733;&#9733;&#9733; (5/5)</option>
                                                <option value="4">&#9733;&#9733;&#9733;&#9733;&#9734; (4/5)</option>
                                                <option value="3">&#9733;&#9733;&#9733;&#9734;&#9734; (3/5)</option>
                                                <option value="2">&#9733;&#9733;&#9734;&#9734;&#9734; (2/5)</option>
                                                <option value="1">&#9733;&#9734;&#9734;&#9734;&#9734; (1/5)</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="email" class="form-label">Votre mail</label>
                                    <input type="email" name="email" id="email" placeholder="Votre mail" required="required" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="review" class="form-label">Commentaire</label>
                                    <textarea rows="4" name="review" id="review" placeholder="Votre commentaire" required="required" class="form-control"></textarea>
                                </div>
                                <button type="submit" class="btn btn-primary">Poster</button>
                            </form>
                        </div>
                    </div>
                </div>
                -->
            </div>
            <div class="col-lg-4">
                <div style="top: 100px;" class="p-4 shadow ml-lg-4 rounded sticky-top">
                    <!--
                    <p class="text-muted"><span class="text-primary h2">{{ $ad->prix }} €</span> par heure</p>
                    <hr class="my-4">
                    -->
                    <form id="booking-form" method="get" action="#" autocomplete="off" class="form">
                        @if (isset(auth()->user()->subscription))
                        <div class="form-group">
                            <center><labe>Appeler au </labe></center>
                            <button type="submit" class="btn btn-success btn-block">{{ $ad->telephone }}</button>
                        </div>
                        @endif
                        <div class="form-group">
                            <button id="openModal" type="button" class="btn btn-primary">Repondre à l'annonce</button>
                        </div>
                    </form>
                    @if (isset(auth()->user()->subscription))
                    <div class="form-group">
                        <button id="openChatModal" type="button" class="btn btn-secondary">discuter avec cette personne</button>
                    </div>
                    @endif
                    <!--
                    <hr class="my-4">
                    <div class="text-center">
                        <p> <a href="#" class="text-secondary text-sm"> <i class="fa fa-heart"></i>Déposer un coud de coeur</a></p>
                        <p class="text-muted text-sm">79 personnes ont kiffé cette annonce </p>
                    </div>
                    -->
                </div>
            </div>
        </div>
    </div>

@endsection

@section('script')
    <script src="{{ asset('js/vue.js') }}"></script>
    <script>
        $(() => {
            const toggleButtons = () => {
                $('#icon').toggle();
                $('#buttons').toggle();
            }
            $('#openModal').click(() => {
                $('#messageModal').modal();
            });
            $('#openChatModal').click(() => {
                $('#chatModal').modal();
            });

            $('#messageForm').submit((e) => {
                let that = e.currentTarget;
                e.preventDefault();
                $('#message').removeClass('is-invalid');
                $('.invalid-feedback').html('');
                toggleButtons();
                $.ajax({
                    method: $(that).attr('method'),
                    url: $(that).attr('action'),
                    data: $(that).serialize()
                })
                    .done((data) => {
                        toggleButtons();
                        $('#messageModal').modal('hide');
                        $('#massageOk').text(data.info).show();
                    })
                    .fail((data) => {
                        toggleButtons();
                        $.each(data.responseJSON.errors, function (i, error) {
                            $(document)
                                .find('[name="' + i + '"]')
                                .addClass('is-invalid')
                                .next()
                                .append(error[0]);
                        });
                    });
            });
        })
    </script>
@endsection