routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


// Auth::routes();
Auth::routes(['verify' => true]);

/*
Route::get('protege', function () {
    return 'affichage de la route protégé';
})->middleware('verified');
*/
//Route::get('/', 'AdController@home')->name('home')->middleware('verified');
Route::get('/', 'AdController@home')->name('home');


Route::get('a-faire', 'AdController@doPage')->name('dopage');

// Authentication Routes...
Route::prefix('connexion')->group(function () {
    Route::get('/', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('/', 'Auth\LoginController@login');
});
Route::post('deconnexion', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::prefix('enregistrement')->group(function () {
    Route::get('/', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/', 'Auth\RegisterController@register');
});
// Password Reset Routes...
Route::prefix('passe')->group(function () {
    Route::get('change', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('change/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('change', 'Auth\ResetPasswordController@reset')->name('password.update');
});



//
//Route::get('{num}', 'NewsController@show')->name('news.show');

//Route::get('news/{num}/edit', 'NewsController@show')->name('news.edit');



//Route::prefix('news')->group(function () {
    //Route::get('news', 'NewsController@index')->name('news.index');
//});



Route::resource('news', 'NewsController')
//    ->middleware('verified')
    ->parameters(['news' => 'news'    ]);   // pour edit

Route::prefix('news')->group(function () {

    Route::get('destroy/{news}', 'NewsController@destroy')->name('news.destroy');
  //  Route::post('change', 'NewsController@update')->name('news.update');

    /*
    Route::get('{num}', 'NewsController@show')->name('news.show');
    Route::get('/', 'NewsController@index')->name('news.index');
    Route::get('{num}/modif', 'NewsController@show')->name('news.modif');
*/
});


Route::resource('annonces', 'AdController')
    ->parameters(['annonces' => 'ad'    ])   // pour edit
    ->except(['index', 'destroy']);


Route::prefix('annonces')->group(function () {

    // affiche une annonce
    Route::get('{ad}/voir', 'AdController@show')->name('annonces.show');

    // affiche la liste
    Route::get('{region?}/{departement?}/{commune?}', 'AdController@index')->name('annonces.index');
    Route::get('{region?}/{departement?}/{commune?}/{cate?}', 'AdController@index')->name('annonces.index');

    // formulaire de recherche
    Route::post('recherche', 'AdController@search')->name('annonces.search')->middleware('ajax');
});


// message
Route::middleware('ajax')->group(function () {
    Route::post('images-save', 'UploadImagesController@store')->name('save-images');
    Route::delete('images-delete', 'UploadImagesController@destroy')->name('destroy-images');
    Route::get('images-server','UploadImagesController@getServerImages')->name('server-images');

    Route::post('message', 'UserController@message')->name('message');
});

// admin
Route::prefix('admin')->middleware('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('admin.index');

    Route::prefix('annonces')->group(function () {
        Route::get('/', 'AdminController@ads')->name('admin.ads');
        Route::middleware('ajax')->group(function () {
            Route::post('approve/{ad}', 'AdminController@approve')->name('admin.approve');
            Route::post('refuse', 'AdminController@refuse')->name('admin.refuse');
        });

        Route::get('obsoletes', 'AdminController@obsoletes')->name('admin.obsoletes');
    });

    Route::prefix('messages')->group(function () {
        Route::get('/', 'AdminController@messages')->name('admin.messages');
        Route::post('approve/{message}', 'AdminController@messageApprove')->name('admin.message.approve');
        Route::post('refuse', 'AdminController@messageRefuse')->name('admin.message.refuse');
    });

});

Route::prefix('admin/annonces')->group(function () {
    Route::middleware('ajax')->group(function () {
        Route::post('addweek/{ad}', 'AdminController@addWeek')->name('admin.addweek');
        Route::delete('destroy/{ad}', 'AdminController@destroy')->name('admin.destroy');
    });
});


// user
Route::prefix('utilisateur')->middleware('user')->group(function () {
    Route::get('/', 'UserController@index')->name('user.index')->middleware('verified');
    Route::prefix('annonces')->group(function () {
        Route::get('actives', 'UserController@actives')->name('user.actives');
        Route::get('obsoletes', 'UserController@obsoletes')->name('user.obsoletes');
        Route::get('attente', 'UserController@attente')->name('user.attente');
    });
    Route::prefix('profil')->group(function () {
        Route::get('email', 'UserController@emailEdit')->name('user.email.edit');
        Route::put('email', 'UserController@emailUpdate')->name('user.email.update');
        Route::get('donnees', 'UserController@data')->name('user.data');
        Route::get('abonnement', 'SubscriptionController@show')->name('user.subscription.select');
        Route::get('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('paiement', 'SubscriptionController@index')->name('user.subscription.create');
        Route::post('annuler', 'SubscriptionController@cancel')->name('user.subscription.cancel');
    });
});

Route::view('group', 'group')->name('group')->middleware('verified');
Route::view('legal', 'legal')->name('legal');
Route::view('confidentialite', 'confidentialite')->name('confidentialite');
Route::view('information', 'information')->name('information');
Route::view('tarif', 'tarif')->name('tarif');


// chat
Route::get('chat', 'ChatsController@index');
Route::get('chat/{user}', 'ChatsController@index')->name('chat.liste');
Route::get('chats', 'ChatsController@fetchMessages');
Route::post('chats', 'ChatsController@sendMessage');

Route::get('locale/{locale}', function ($locale){
    session()->put('locale', $locale);
    return redirect()->back();
});



Route::get('payment', 'PayPalController@payment')->name('payment');
Route::get('cancel', 'PayPalController@cancel')->name('payment.cancel');
Route::get('payment/success', 'PayPalController@success')->name('payment.success');

/*
// paypal
Route::get('abonnement', 'PaypalController@index')->name('subscription');
Route::get('paypal/express-checkout', 'PaypalController@expressCheckout')->name('paypal.express-checkout');
Route::get('paypal/express-cancel/{invoice_id?}', 'PaypalController@expressCancel')->name('paypal.express-cancel');
Route::get('paypal/express-checkout-success', 'PaypalController@expressCheckoutSuccess');
Route::post('paypal/notify', 'PaypalController@notify');
*/


// Stripe

Route::get('abonnement', 'SubscriptionController@show')->name('abonnement');
Route::post('order-post', ['as'=>'order-post','uses'=>'SubscriptionController@orderPost']);

app/Models/News.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class News extends Model
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'texte',
        'category',
        'active',
    ];

    public function photos()
    {
        return $this->hasMany(Upload::class);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\News;
use Illuminate\Support\Str;

use App\Repositories\NewsRepository;

use App\Http\Requests\NewsStore;
use App\Models\Upload;



class NewsController extends Controller
{

    /**
     * News repository.
     *
     * @var App\Repositories\NewsRepository
     */
    protected $newsRepository;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct(NewsRepository $newsRepository)
    {
        $this->newsRepository = $newsRepository;
    }


    /**
     * affiche la liste des articles
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = $this->newsRepository->last(8);

       return view('news.list', compact('news'));
    }

    /**
     * affiche la page pour creer un article
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        if(!$request->session()->has('index')) {
            $request->session()->put('index', Str::random(30));
        }

        $categories['news'] = 'Article';
        $categories['coverage'] = 'Reportage';

        return view('news.create', compact('categories'));
    }

    /**
     * enregistre la nouvelle annonce
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $news = $this->newsRepository->create([
            'title' => $request->title,
            'texte' => $request->texte,
            'category' => $request->category,
            'active' => true
        ]);

        if($request->session()->has('index')) {
            $index = $request->session()->get('index');
            Upload::whereIndex($index)->update(['news_id' => $news->id, 'index' => 0]);
        }

        $news = $this->newsRepository->last(8);
        return view('news.list', compact('news'));
    }

    /**
     * affiche un article
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(News $news)
    {
        //$this->authorize('show', $ad);
        $photos = $this->newsRepository->getPhotos($news);
        return view('news.show', compact('news', 'photos'));
    }

    /**
     * affiche la page pour modifier un article
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(News $news)
    {

        //$this->authorize('show', $ad);
        $photos = $this->newsRepository->getPhotos($news);

        $categories['news'] = 'Article';
        $categories['coverage'] = 'Reportage';

        return view('news.edit', compact('news', 'photos', 'categories'));
    }

    /**
     * modifie un article
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, News $news)
    {

        //$this->authorize('manage', $news);
        $this->newsRepository->update($news, $request->all());
        $request->session()->flash('status', "L'annonce a bien été modifiée.");
        return back();
    }


    /**
     * supprime un article
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, News $news)
    {

        // $this->authorize('manage', $news);
        $this->newsRepository->delete($news);
        $request->session()->flash('status', "L'article a bien été supprimée.");

        $news = $this->newsRepository->last(8);

        return view('news.list', compact('news'));
    }

}

resources/views/news/confirm.blade.php
@extends('layouts.app')
@section('content')
    <div class="container py-5">
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{ asset('img/confirm.jpg') }}" alt="">
                </div>
                <div class="col-md-8">
                    <h1 class="display-4">Confirmation d'article</h1>
                    <p class="lead">Votre est validé</p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/news/coverage.blade.php
<div class="card h-100 border-0 shadow card-zoom">
    <div class="card-img-top overflow-hidden grient-overlay ad-card-img-div-top">
        @if($news->photos->isNotEmpty())
            <img src="{{ asset('thumbs/' . $news->photos->first()->filename) }}" alt="" class="rounded img-fluid" width="100%">
        @else
            <img src="{{ asset('thumbs/nopicture.jpg') }}" alt="" class="img-fluid" width="100%">
        @endif
        <a href="{{ route('annonces.show', $news->id) }}" class="tile-link"></a>
    </div>
    <div class="card-by d-flex align-bottom carg-overlay">
        <div class="w-100 coverage-back">
            <div class="card-title">{{ $news->title }}</div>

            <a href="{{ route('news.show', $news->id) }}" class="tile-link"></a>
        </div>
    </div>
</div>

resources/views/news/create.blade.php
@extends('layouts.app')
@section('content')

    <div class="container py-5">
        @guest
            <div class="alert alert-warning text-center alert-dismissible fade show" role="alert">
                Vous n'êtes pas connecté, vous ne pourrez pas modifier votre annonce ultérieurement<br>
                La création d'un compte est gratuite et vous offre de nombreuses fonctionnalités
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endguest
        <div class="shadow">
            <h2>Création de votre articles</h2>
            <div class="col-md-12">
                <div class="form-group">
                    <label>Une photo qui sera affiché avec le titre sur la page</label>
                    <form method="post" action="{{ route('save-images') }}" enctype="multipart/form-data" class="dropzone" id="my-dropzone">
                        @csrf
                        <div class="dz-message">
                            <div class="col-xs-8">
                                <div class="message">
                                    <p>Déposez vos photos ici ou cliquez</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <form method="POST" action="{{ route('news.store') }}">
                    @csrf
                    @include('partials.form-group', [
                       'title' => 'Titre',
                       'type' => 'text',
                       'name' => 'title',
                       'required' => true,
                   ])

                    <div class="form-group">
                        <label for="texte">Texte de votre article</label>
                        <textarea class="form-control{{ $errors->has('texte') ? ' is-invalid' : '' }} tinymce-editor" id="texte" name="texte" rows="10" maxlength="5000">{{ old('texte', isset($value) ? $value : '') }}</textarea>
                        @if ($errors->has('texte'))
                            <div class="invalid-feedback">
                                {{ $errors->first('texte') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="category">Catégorie</label>
                        {{ Form::select('category', $categories, null, array('class' => 'custom-select')) }}
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Valider</button>
                    <br/><br/>
                </form>



                </div>
            </div>
        </div>
        @endsection
        @section('script')


            <script>


                Dropzone.options.myDropzone = {
                    uploadMultiple: true,
                    parallelUploads: 3,
                    maxFilesize: 3,
                    maxFiles: 3,
                    dictMaxFilesExceeded : 'Vous ne pouvez charger que 3 photos',
                    previewTemplate: document.querySelector('#preview').innerHTML,
                    addRemoveLinks: true,
                    acceptedFiles: 'image/*',
                    dictInvalidFileType : 'Type de fichier interdit',
                    dictRemoveFile: 'Supprimer',
                    dictFileTooBig: 'L\'image fait plus de 3 Mo',
                    timeout: 10000,
                    init () {
                        const myDropzone = this;
                        $.get('{{ route('server-images') }}', data => {
                            $.each(data.images, (key, value) => {
                                const mockFile = {
                                    name: value.original,
                                    size: value.size,
                                    dataURL: '{{ url('images') }}' + '/' + value.server
                                };
                                myDropzone.files.push(mockFile);
                                myDropzone.emit("addedfile", mockFile);
                                myDropzone.createThumbnailFromUrl(mockFile,
                                    myDropzone.options.thumbnailWidth,
                                    myDropzone.options.thumbnailHeight,
                                    myDropzone.options.thumbnailMethod, true, (thumbnail) => {
                                        myDropzone.emit('thumbnail', mockFile, thumbnail);
                                    });
                                myDropzone.emit('complete', mockFile);
                            });
                        });
                        this.on("removedfile", file => {
                            $.ajax({
                                method: 'delete',
                                url: '{{ route('destroy-images') }}',
                                data: { name: file.name, _token: $('[name="_token"]').val() }
                            });
                        });
                    }
                };

            </script>

                <script src="https://cdn.tiny.cloud/1/8gw0lshon0bn94yzknjer4d2p46xizbxm2r9yp1v6rglyawn/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
            <script type="text/javascript">
                tinymce.init({
                    selector: 'textarea.tinymce-editor',
                    //height: 100,
                    menubar: false,
                    plugins: [
                        'advlist autolink lists link image charmap print preview anchor',
                        'searchreplace visualblocks code fullscreen',
                        'insertdatetime media table paste code help wordcount'
                    ],
                    toolbar: 'undo redo | formatselect | ' +
                        'bold italic backcolor | alignleft aligncenter ' +
                        'alignright alignjustify | bullist numlist outdent indent | ' +
                        'removeformat | help',
                    toolbar_mode: 'floating'
                });
            </script>

@endsection

resources/views/news/edit.blade.php
@extends('layouts.app')
@section('content')

    <div class="container py-5">
        @guest
            <div class="alert alert-warning text-center alert-dismissible fade show" role="alert">
                Vous n'êtes pas connecté, vous ne pourrez pas modifier votre annonce ultérieurement<br>
                La création d'un compte est gratuite et vous offre de nombreuses fonctionnalités
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endguest
        <div class="shadow">
            <h2>Modification de votre article</h2>
            <div class="col-md-12">

                @if(session()->has('status'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <form method="POST" action="{{ route('news.update', $news->id) }}">
                    @method('PUT')
                    @csrf
                    @include('partials.form-group', [
                       'title' => 'Titre',
                       'type' => 'text',
                       'name' => 'title',
                       'value' => $news->title,
                       'required' => true,
                   ])

                    <div class="form-group">
                        <label for="texte">Texte de votre article</label>
                        <textarea class="form-control{{ $errors->has('texte') ? ' is-invalid' : '' }} tinymce-editor" id="texte" name="texte" rows="10"
                                  maxlength="5000">{{ old('texte', isset($value) ? $value : $news->texte) }}</textarea>
                        @if ($errors->has('texte'))
                            <div class="invalid-feedback">
                                {{ $errors->first('texte') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="category">Catégorie</label>
                        {{ Form::select('category', $categories, null, array('class' => 'custom-select')) }}
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary">Valider</button>
                    <br/><br/>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('script')


    <script>
        Dropzone.options.myDropzone = {
            uploadMultiple: true,
            parallelUploads: 3,
            maxFilesize: 3,
            maxFiles: 3,
            dictMaxFilesExceeded: 'Vous ne pouvez charger que 3 photos',
            previewTemplate: document.querySelector('#preview').innerHTML,
            addRemoveLinks: true,
            acceptedFiles: 'image/*',
            dictInvalidFileType: 'Type de fichier interdit',
            dictRemoveFile: 'Supprimer',
            dictFileTooBig: 'L\'image fait plus de 3 Mo',
            timeout: 10000,
            init() {
                const myDropzone = this;
                $.get('{{ route('server-images') }}', data => {
                    $.each(data.images, (key, value) => {
                        const mockFile = {
                            name: value.original,
                            size: value.size,
                            dataURL: '{{ url('images') }}' + '/' + value.server
                        };
                        myDropzone.files.push(mockFile);
                        myDropzone.emit("addedfile", mockFile);
                        myDropzone.createThumbnailFromUrl(mockFile,
                            myDropzone.options.thumbnailWidth,
                            myDropzone.options.thumbnailHeight,
                            myDropzone.options.thumbnailMethod, true, (thumbnail) => {
                                myDropzone.emit('thumbnail', mockFile, thumbnail);
                            });
                        myDropzone.emit('complete', mockFile);
                    });
                });
                this.on("removedfile", file => {
                    $.ajax({
                        method: 'delete',
                        url: '{{ route('destroy-images') }}',
                        data: {name: file.name, _token: $('[name="_token"]').val()}
                    });
                });
            }
        };

    </script>

    <script src="https://cdn.tiny.cloud/1/8gw0lshon0bn94yzknjer4d2p46xizbxm2r9yp1v6rglyawn/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: 'textarea.tinymce-editor',
            //height: 100,
            menubar: false,
            plugins: [
                'advlist autolink lists link image charmap print preview anchor',
                'searchreplace visualblocks code fullscreen',
                'insertdatetime media table paste code help wordcount'
            ],
            toolbar: 'undo redo | formatselect | ' +
                'bold italic backcolor | alignleft aligncenter ' +
                'alignright alignjustify | bullist numlist outdent indent | ' +
                'removeformat | help',
            toolbar_mode: 'floating'
        });
    </script>

@endsection

resources/views/news/list.blade.php
@extends('layouts.app')
@section('content')

    <section class="py-6 bg-gray-100">
        <div class="container">
            <div class="row mb-5">
                <div class="col-md-8">
                    <p class="subtitle text-secondary">Les dernières informations </p>
                    <h2>Articles récents</h2>
                </div>
            </div>

            <div class="row">

                @foreach($news as $new)
                    <div class="col-md-6 col-sm-12 pt-6 mt-2">
                        @include('news.new', ['news' =>$new])
                    </div>
                @endforeach

            </div>

        </div>
    </section>

    <!-- Instagram-->
    <section>
        <div class="container-fluid px-0">
            <div class="swiper-container instagram-slider">
                <div class="swiper-wrapper">

                    <?php for ($i = 1; $i < 20; $i++) { ?>
                    <div class="swiper-slide overflow-hidden"><a href="#"><img src="img/instagram/<?php echo $i ?>.jpg" alt="" class="img-fluid hover-scale"></a></div>
                    <?php } ?>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('script')
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
@endsection

resources/views/news/new.blade.php
<div class="card h-100 border-0 shadow card-zoom">
    <div class="card-img-top overflow-hidden grient-overlay ad-card-img-div-top">
        @if($news->photos->isNotEmpty())
            <img src="{{ asset('thumbs/' . $news->photos->first()->filename) }}" alt="" class="rounded img-fluid" width="100%">
        @else
            <img src="{{ asset('thumbs/nopicture.jpg') }}" alt="" class="img-fluid" width="100%">
        @endif
        <a href="{{ route('annonces.show', $news->id) }}" class="tile-link"></a>
        <!--
    <div class="card-img-overlay-top text-right"><a href="javascript: void();" class="card-fav-icon position-relative z-index-40">
            <svg class="svg-icon text-white">
                <use xlink:href="#heart-1"> </use>
            </svg></a>
    </div>
    -->
    </div>
    <div class="card-body d-flex align-items-center ">
        <div class="w-100">
            <h6 class="card-title">{{ $news->title }}</h6>
            <p class="text-gray-700 text-sm my-3 ad-text">

                {{ strlen($news->texte) > 200 ? substr($news->texte, 0, 200).'...' : $news->texte }}
            </p>

            <a href="{{ route('news.show', $news->id) }}" class="tile-link"></a>
        </div>
    </div>
</div>

resources/views/news/new_home.blade.php
<div class="card h-60 border-0 shadow card-zoom  overflow-hidden" >
    <div class="row">

        <div class="col-md-5">
            @if($news->photos->isNotEmpty())
                <img src="{{ asset('thumbs/' . $news->photos->first()->filename) }}" alt="" class="rounded img-fluid" width="100%">
            @else
                <img src="{{ asset('thumbs/nopicture.jpg') }}" alt="" class="img-fluid">
            @endif
            <a href="{{ route('news.show', $news->id) }}" class="tile-link"></a>

        </div>
        <div class="col-md-7" style="padding: 0; margin: 0">
            <div class="text-gray-700 text-sm my-3 ad-text">

                {{ strlen($news->title) > 35 ? substr($news->title, 0, 35).'...' : $news->title }}
            </div>
            <a href="{{ route('news.show', $news->id) }}" class="tile-link"></a>
        </div>
    </div>

</div>